### ISSUE TITLE
Mulitple errors thrown in traceback

### ISSUE THREAD

**Issue by FletcherMunson** [ztgrace/changeme#14]
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "./changeme.py", line 558, in do_scan
    fp = fingerprints.get_nowait()
    self._target(*self._args, **self._kwargs)
  File "./changeme.py", line 558, in do_scan
    fp = fingerprints.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
  File "<string>", line 2, in get_nowait
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
Empty
    raise convert_to_error(kind, result)
Empty

**Comment by FletcherMunson** [comment]
This was right after a 'git pull'. I ran it about 15 minutes later without error.
