### ISSUE TITLE
Run changeme outside of project directory

### ISSUE THREAD

**Issue by sil3ntcor3** [ztgrace/changeme#45]
Changeme fails to run with the following output:

/opt/changeme/changeme.py -d PTDS_scan_1.xml

[09:12:21][core][_validate_args] Delay is set to 500 milliseconds
[09:12:21][core][_validate_args] http
[09:12:23][core][check_version] Unable to retrieve latest changeme version.
Traceback (most recent call last):
  File "/opt/changeme/changeme.py", line 6, in <module>
    core.main()
  File "/opt/changeme/changeme/core.py", line 48, in main
    creds = load_creds(config)
  File "/opt/changeme/changeme/core.py", line 260, in load_creds
    protocols = next(os.walk('creds'))[1]
StopIteration

/opt/changeme/changeme.py -d 10.154.1.1

[13:40:18][core][_validate_args] Delay is set to 500 milliseconds
[13:40:18][core][_validate_args] http
[13:40:20][core][check_version] Unable to retrieve latest changeme version.
Traceback (most recent call last):
  File "/opt/changeme/changeme.py", line 6, in <module>
    core.main()
  File "/opt/changeme/changeme/core.py", line 48, in main
    creds = load_creds(config)
  File "/opt/changeme/changeme/core.py", line 260, in load_creds
    protocols = next(os.walk('creds'))[1]
StopIteration

**Comment by ztgrace** [comment]
Thanks for the bug report. So according to the Python [documentation](https://docs.python.org/2/library/exceptions.html#exceptions.StopIteration), a generator in python should always raise a `StopIteration` exception when there's no more values in the generator. Some built-in functions like `for` automatically handle this exception and terminate the loop. Since I was calling `next` directly, the uncaught exception gets raised. Now the crazy part is that the error and this is some of the oldest code in changeme and I'm baffled why this doesn't throw an exception all of the time and you're the first to hit this error.

 Until 1.0.3 gets published, swapping line 260 with `protocols = [proto for proto in os.walk('creds')][0][1]` or running the development branch should fix the issue.

* https://docs.python.org/2/library/exceptions.html#exceptions.StopIteration
* https://stackoverflow.com/questions/16465313/how-yield-catches-stopiteration-exception

**Comment by sil3ntcor3** [comment]
Looks like I'm getting a _newish_ error now. I tried both the swapping line 260 with the new code and running the dev branch. 

Traceback (most recent call last):
  File "/opt/changeme/changeme.py", line 6, in <module>
    core.main()
  File "/opt/changeme/changeme/core.py", line 48, in main
    creds = load_creds(config)
  File "/opt/changeme/changeme/core.py", line 260, in load_creds
    protocols = [ proto for proto in os.walk('creds')][0][1]
IndexError: list index out of range

**Comment by ztgrace** [comment]
Ok, I can finally reproduce it (I was shooting in the dark earlier). It looks like you're running `/opt/changeme/changeme.py` from outside of the project directory `/opt/changeme/`. So if you `cd /opt/changeme/` then run `./changeme.py -d PTDS_scan_1.xml` it should work better for you.

I'm going to rename this issue to better reflect the issue and work on getting this resolved for the next release.

Thanks again for the bug report and troubleshooting.
